import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(19.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.primary,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      radioTheme: RadioThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.onPrimaryContainer;
          }
          return colorScheme.onSurface;
        }),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.onPrimaryContainer;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 2,
        space: 2,
        color: appTheme.teal30003,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodySmall: TextStyle(
          color: appTheme.gray600,
          fontSize: 10.fSize,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: appTheme.blueGray700,
          fontSize: 35.fSize,
          fontFamily: 'Red Rose',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: appTheme.blueGray800,
          fontSize: 12.fSize,
          fontFamily: 'Red Rose',
          fontWeight: FontWeight.w700,
        ),
        labelMedium: TextStyle(
          color: appTheme.blueGray800,
          fontSize: 10.fSize,
          fontFamily: 'Red Rose',
          fontWeight: FontWeight.w700,
        ),
        labelSmall: TextStyle(
          color: appTheme.blueGray800,
          fontSize: 8.fSize,
          fontFamily: 'Red Rose',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 20.fSize,
          fontFamily: 'Red Rose',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 16.fSize,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: appTheme.blueGray800,
          fontSize: 14.fSize,
          fontFamily: 'Red Rose',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF519E98),
    primaryContainer: Color(0XFF363636),
    secondary: Color(0XFF363636),
    secondaryContainer: Color(0XFFBBBBC6),
    tertiary: Color(0XFF363636),
    tertiaryContainer: Color(0XFFBBBBC6),

    // Background colors
    background: Color(0XFF363636),

    // Surface colors
    surface: Color(0XFF363636),
    surfaceTint: Color(0XFF363636),
    surfaceVariant: Color(0XFFBBBBC6),

    // Error colors
    error: Color(0XFF363636),
    errorContainer: Color(0XFFBBBBC6),
    onError: Color(0XFFFFFFFF),
    onErrorContainer: Color(0XFF363636),

    // On colors(text colors)
    onBackground: Color(0XFFFFFFFF),
    onInverseSurface: Color(0XFFFFFFFF),
    onPrimary: Color(0XFF363636),
    onPrimaryContainer: Color(0XFFFFFFFF),
    onSecondary: Color(0XFFFFFFFF),
    onSecondaryContainer: Color(0XFF363636),
    onTertiary: Color(0XFFFFFFFF),
    onTertiaryContainer: Color(0XFF363636),

    // Other colors
    outline: Color(0XFF363636),
    outlineVariant: Color(0XFF363636),
    scrim: Color(0XFF363636),
    shadow: Color(0XFF363636),

    // Inverse colors
    inversePrimary: Color(0XFF363636),
    inverseSurface: Color(0XFF363636),

    // Pending colors
    onSurface: Color(0XFFFFFFFF),
    onSurfaceVariant: Color(0XFF363636),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray10026 => Color(0X26CCCCCC);
  Color get blueGray200 => Color(0XFFB1B1D2);
  Color get blueGray300 => Color(0XFF8E8FA5);
  Color get blueGray400 => Color(0XFF848A93);
  Color get blueGray40001 => Color(0XFF888888);
  Color get blueGray700 => Color(0XFF2F6B65);
  Color get blueGray70001 => Color(0XFF306D67);
  Color get blueGray800 => Color(0XFF364356);

  // BlueGrayf
  Color get blueGray503f => Color(0X3FEDEFEF);

  // Cyan
  Color get cyan100 => Color(0XFFB0EFEA);

  // Gray
  Color get gray100 => Color(0XFFF3F9F9);
  Color get gray300 => Color(0XFFE3E4E4);
  Color get gray400 => Color(0XFFBBBCC7);
  Color get gray500 => Color(0XFF949494);
  Color get gray50026 => Color(0X269E9E9E);
  Color get gray600 => Color(0XFF7B7B7B);
  Color get gray60001 => Color(0XFF696A82);
  Color get gray60002 => Color(0XFF757575);

  // Red
  Color get red500 => Color(0XFFEA4335);
  Color get red50001 => Color(0XFFF44336);
  Color get red50002 => Color(0XFFFF3722);

  // Teal
  Color get teal300 => Color(0XFF62B8B1);
  Color get teal30001 => Color(0XFF62B7B0);
  Color get teal30002 => Color(0XFF52BFB4);
  Color get teal30003 => Color(0XFF64BAB3);
  Color get teal30004 => Color(0XFF66BCB5);
  Color get teal30014 => Color(0X1464B9B3);
  Color get teal400 => Color(0XFF3A9189);
  Color get teal50 => Color(0XFFD3ECEC);
  Color get teal500 => Color(0XFF00B67A);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
